# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T10:13:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AccountId(RootModel[constr(pattern=r'[0-9]{12}', min_length=12, max_length=12)]):
    root: constr(pattern=r'[0-9]{12}', min_length=12, max_length=12)


class AmazonResourceName(
    RootModel[
        constr(
            pattern=r'arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+',
            min_length=1,
            max_length=1011,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+', min_length=1, max_length=1011
    )


class ConflictException(RootModel[Any]):
    root: Any


class ConnectionArn(
    RootModel[
        constr(
            pattern=r'arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+', min_length=0, max_length=256
        )
    ]
):
    root: constr(
        pattern=r'arn:aws(-[\w]+)*:.+:.+:[0-9]{12}:.+', min_length=0, max_length=256
    )


class ConnectionName(
    RootModel[constr(pattern=r'[\s\S]*', min_length=1, max_length=32)]
):
    root: constr(pattern=r'[\s\S]*', min_length=1, max_length=32)


class ConnectionStatus(Enum):
    PENDING = 'PENDING'
    AVAILABLE = 'AVAILABLE'
    ERROR = 'ERROR'


class DeleteConnectionInput(BaseModel):
    ConnectionArn_1: ConnectionArn = Field(..., alias='ConnectionArn')


class DeleteConnectionOutput(BaseModel):
    pass


class DeleteHostOutput(BaseModel):
    pass


class GetConnectionInput(BaseModel):
    ConnectionArn_1: ConnectionArn = Field(..., alias='ConnectionArn')


class HostArn(
    RootModel[
        constr(
            pattern=r'arn:aws(-[\w]+)*:codestar-connections:.+:[0-9]{12}:host\/.+',
            min_length=0,
            max_length=256,
        )
    ]
):
    root: constr(
        pattern=r'arn:aws(-[\w]+)*:codestar-connections:.+:[0-9]{12}:host\/.+',
        min_length=0,
        max_length=256,
    )


class HostName(RootModel[constr(pattern=r'.*', min_length=1, max_length=64)]):
    root: constr(pattern=r'.*', min_length=1, max_length=64)


class HostStatus(RootModel[constr(pattern=r'.*', min_length=1, max_length=64)]):
    root: constr(pattern=r'.*', min_length=1, max_length=64)


class HostStatusMessage(RootModel[str]):
    root: str


class LimitExceededException(RootModel[Any]):
    root: Any


class ListTagsForResourceInput(BaseModel):
    ResourceArn: AmazonResourceName


class MaxResults(RootModel[conint(ge=0, le=100)]):
    root: conint(ge=0, le=100)


class NextToken(RootModel[constr(pattern=r'.*', min_length=1, max_length=1024)]):
    root: constr(pattern=r'.*', min_length=1, max_length=1024)


class ProviderType(Enum):
    Bitbucket = 'Bitbucket'
    GitHub = 'GitHub'
    GitHubEnterpriseServer = 'GitHubEnterpriseServer'


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ResourceUnavailableException(RootModel[Any]):
    root: Any


class SecurityGroupId(
    RootModel[constr(pattern=r'sg-\w{8}(\w{9})?', min_length=11, max_length=20)]
):
    root: constr(pattern=r'sg-\w{8}(\w{9})?', min_length=11, max_length=20)


class SecurityGroupIds(RootModel[List[SecurityGroupId]]):
    root: List[SecurityGroupId] = Field(..., max_length=10, min_length=1)


class SubnetId(
    RootModel[constr(pattern=r'subnet-\w{8}(\w{9})?', min_length=15, max_length=24)]
):
    root: constr(pattern=r'subnet-\w{8}(\w{9})?', min_length=15, max_length=24)


class SubnetIds(RootModel[List[SubnetId]]):
    root: List[SubnetId] = Field(..., max_length=10, min_length=1)


class TagKey(RootModel[constr(pattern=r'.*', min_length=1, max_length=128)]):
    root: constr(pattern=r'.*', min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=0)


class TagResourceOutput(BaseModel):
    pass


class TagValue(RootModel[constr(pattern=r'.*', min_length=0, max_length=256)]):
    root: constr(pattern=r'.*', min_length=0, max_length=256)


class TlsCertificate(
    RootModel[constr(pattern=r'[\s\S]*', min_length=1, max_length=16384)]
):
    root: constr(pattern=r'[\s\S]*', min_length=1, max_length=16384)


class UnsupportedOperationException(RootModel[Any]):
    root: Any


class UntagResourceInput(BaseModel):
    ResourceArn: AmazonResourceName
    TagKeys: TagKeyList


class UntagResourceOutput(BaseModel):
    pass


class UpdateHostOutput(BaseModel):
    pass


class Url(RootModel[constr(pattern=r'.*', min_length=1, max_length=512)]):
    root: constr(pattern=r'.*', min_length=1, max_length=512)


class VpcId(
    RootModel[constr(pattern=r'vpc-\w{8}(\w{9})?', min_length=12, max_length=21)]
):
    root: constr(pattern=r'vpc-\w{8}(\w{9})?', min_length=12, max_length=21)


class XAmzTarget(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_CreateConnection = 'com.amazonaws.codestar.connections.CodeStar_connections_20191201.CreateConnection'


class XAmzTarget1(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_CreateHost = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.CreateHost'
    )


class XAmzTarget2(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_DeleteConnection = 'com.amazonaws.codestar.connections.CodeStar_connections_20191201.DeleteConnection'


class XAmzTarget3(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_DeleteHost = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.DeleteHost'
    )


class XAmzTarget4(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_GetConnection = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.GetConnection'
    )


class XAmzTarget5(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_GetHost = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.GetHost'
    )


class XAmzTarget6(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_ListConnections = 'com.amazonaws.codestar.connections.CodeStar_connections_20191201.ListConnections'


class XAmzTarget7(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_ListHosts = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.ListHosts'
    )


class XAmzTarget8(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_ListTagsForResource = 'com.amazonaws.codestar.connections.CodeStar_connections_20191201.ListTagsForResource'


class XAmzTarget9(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_TagResource = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.TagResource'
    )


class XAmzTarget10(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_UntagResource = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.UntagResource'
    )


class XAmzTarget11(Enum):
    com_amazonaws_codestar_connections_CodeStar_connections_20191201_UpdateHost = (
        'com.amazonaws.codestar.connections.CodeStar_connections_20191201.UpdateHost'
    )


class Connection(BaseModel):
    ConnectionArn_1: Optional[ConnectionArn] = Field(None, alias='ConnectionArn')
    ConnectionName_1: Optional[ConnectionName] = Field(None, alias='ConnectionName')
    ConnectionStatus_1: Optional[ConnectionStatus] = Field(
        None, alias='ConnectionStatus'
    )
    HostArn_1: Optional[HostArn] = Field(None, alias='HostArn')
    OwnerAccountId: Optional[AccountId] = None
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')


class ConnectionList(RootModel[List[Connection]]):
    root: List[Connection]


class DeleteHostInput(BaseModel):
    HostArn_1: HostArn = Field(..., alias='HostArn')


class GetConnectionOutput(BaseModel):
    Connection_1: Optional[Connection] = Field(None, alias='Connection')


class GetHostInput(BaseModel):
    HostArn_1: HostArn = Field(..., alias='HostArn')


class ListConnectionsInput(BaseModel):
    HostArnFilter: Optional[HostArn] = None
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ProviderTypeFilter: Optional[ProviderType] = None


class ListConnectionsOutput(BaseModel):
    Connections: Optional[ConnectionList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListHostsInput(BaseModel):
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class Tag(BaseModel):
    Key: TagKey
    Value: TagValue


class TagList(RootModel[List[Tag]]):
    root: List[Tag] = Field(..., max_length=200, min_length=0)


class TagResourceInput(BaseModel):
    ResourceArn: AmazonResourceName
    Tags: TagList


class VpcConfiguration(BaseModel):
    SecurityGroupIds_1: SecurityGroupIds = Field(..., alias='SecurityGroupIds')
    SubnetIds_1: SubnetIds = Field(..., alias='SubnetIds')
    TlsCertificate_1: Optional[TlsCertificate] = Field(None, alias='TlsCertificate')
    VpcId_1: VpcId = Field(..., alias='VpcId')


class CreateConnectionInput(BaseModel):
    ConnectionName_1: ConnectionName = Field(..., alias='ConnectionName')
    HostArn_1: Optional[HostArn] = Field(None, alias='HostArn')
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')
    Tags: Optional[TagList] = None


class CreateConnectionOutput(BaseModel):
    ConnectionArn_1: ConnectionArn = Field(..., alias='ConnectionArn')
    Tags: Optional[TagList] = None


class CreateHostInput(BaseModel):
    Name: HostName
    ProviderEndpoint: Url
    ProviderType_1: ProviderType = Field(..., alias='ProviderType')
    Tags: Optional[TagList] = None
    VpcConfiguration_1: Optional[VpcConfiguration] = Field(
        None, alias='VpcConfiguration'
    )


class CreateHostOutput(BaseModel):
    HostArn_1: Optional[HostArn] = Field(None, alias='HostArn')
    Tags: Optional[TagList] = None


class GetHostOutput(BaseModel):
    Name: Optional[HostName] = None
    ProviderEndpoint: Optional[Url] = None
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')
    Status: Optional[HostStatus] = None
    VpcConfiguration_1: Optional[VpcConfiguration] = Field(
        None, alias='VpcConfiguration'
    )


class Host(BaseModel):
    HostArn_1: Optional[HostArn] = Field(None, alias='HostArn')
    Name: Optional[HostName] = None
    ProviderEndpoint: Optional[Url] = None
    ProviderType_1: Optional[ProviderType] = Field(None, alias='ProviderType')
    Status: Optional[HostStatus] = None
    StatusMessage: Optional[HostStatusMessage] = None
    VpcConfiguration_1: Optional[VpcConfiguration] = Field(
        None, alias='VpcConfiguration'
    )


class HostList(RootModel[List[Host]]):
    root: List[Host]


class ListHostsOutput(BaseModel):
    Hosts: Optional[HostList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListTagsForResourceOutput(BaseModel):
    Tags: Optional[TagList] = None


class UpdateHostInput(BaseModel):
    HostArn_1: HostArn = Field(..., alias='HostArn')
    ProviderEndpoint: Optional[Url] = None
    VpcConfiguration_1: Optional[VpcConfiguration] = Field(
        None, alias='VpcConfiguration'
    )
